name: Terragrunt Overlay
description: Apply default and overlayed Terragrunt configurations with GitHub Actions.
author: Josh Feierman <josh@sqljosh.com>
runs:
  using: docker
  image: 'Dockerfile'
inputs:
  base-directory:
    description: |
      The base directory for all Terragrunt configurations. Defaults to the root of the
      repository.
    default: "."
    required: false
  terraform-command:
    description: |
      The Terraform command to run.
    required: true
  token:
    description: |
      The token to use when interacting with the GitHub API. This can generally be set to the
      default token.
    required: true