name: Terragrunt Overlay
description: Apply default and overlayed Terragrunt configurations with GitHub Actions.
author: Josh Feierman <josh@sqljosh.com>
runs:
  # using: docker
  # image: 'Dockerfile'
  using: composite
  steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: run Terragrunt
      run: go run main.go
      shell: bash
      env:
        INPUT_BASE-DIRECTORY: ${{ inputs.base-directory }}
        INPUT_TERRAFORM-COMMAND: ${{ inputs.terraform-command }}
        INPUT_TOKEN: ${{ inputs.token }}
inputs:
  base-directory:
    description: |
      The base directory for all Terragrunt configurations. Defaults to the root of the
      repository.
    default: "."
    required: false
  terraform-command:
    description: |
      The Terraform command to run.
    required: true
  token:
    description: |
      The token to use when interacting with the GitHub API. This can generally be set to the
      default token.
    required: true
    default: ${{ github.token }}
  ref:
    description: The ref of the Action. Don't set this!
    default: ${{ github.action_ref }}