name: Terragrunt Overlay
description: Apply default and overlayed Terragrunt configurations with GitHub Actions.
author: Josh Feierman <josh@sqljosh.com>
runs:
  using: docker
  image: 'Dockerfile'
  # using: composite
  # steps:
  #   - name: setup go
  #     uses: actions/setup-go@v3
  #     with:
  #       go-version-file: ${{github.action_path}}/go.mod
  #   - name: install tgswitch and tfenv
  #     shell: bash
  #     env:
  #       TG_VERSION: ${{ inputs.terragrunt-version }}
  #     run: |
  #       if [ -z "$(command -v tgswitch)" ]; then
  #         curl -L https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh | bash -s -- -b ${HOME}/.bin
  #         echo ${HOME}/.bin >> ${GITHUB_PATH}
  #         export PATH=${HOME}/.bin:${PATH}
  #       fi
  #       if [ -z "$(command -v tfenv)" ]; then
  #         echo "${HOME}/.tfenv/bin" >> ${GITHUB_PATH}
  #         export PATH=${HOME}/.tfenv/bin:${PATH}
  #         git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
  #       fi
  #       cd "${{ inputs.base-directory }}"
  #       tgswitch -b ${HOME}/.bin/terragrunt
  #       tfenv use
  #   - name: run Terragrunt
  #     run: go build -o ${HOME}/.bin/action-terragrunt main.go
  #     shell: bash
  #     working-directory: "${{github.action_path}}"
  #   - name: run Action
  #     run: action-terragrunt
  #     shell: bash
  #     env:
  #       INPUT_BASE-DIRECTORY: ${{ inputs.base-directory }}
  #       INPUT_TERRAFORM-COMMAND: ${{ inputs.terraform-command }}
  #       INPUT_TOKEN: ${{ inputs.token }}
inputs:
  base-directory:
    description: |
      The base directory for all Terragrunt configurations. Defaults to the root of the
      repository.
    default: "."
    required: false
  terraform-command:
    description: |
      The Terraform command to run.
    required: true
  token:
    description: |
      The token to use when interacting with the GitHub API. This can generally be set to the
      default token.
    required: true
    default: ${{ github.token }}
  terragrunt-version:
    description: >
      The version of Terragrunt to use. This sets the `TG_VERSION` environment variable, causing the
      `tgswitch` tool to select the specified version of Terragrunt. If this is unset, `tgswitch`
      will attempt to determine the correct version of Terragrunt to install using the logic
      detailed in the [`tgswitch` repository](https://github.com/warrensbox/tgswitch).
    required: false
  terraform-version:
    description: >
      The version of Terraform to use. This sets the `TFENV_TERRAFORM_VERSION` environment variable,
      causing the `tfenv` tool to select the specified version of Terraform. If this is unset,
      `tfenv` will attempt to determine the correct version of Terraform to install using the logic
      detailed in the [`tfenv` repository](https://github.com/tfutils/tfenv).
  enable-debug-logging:
    required: false
    default: "false"
    description: >
      If set to 'true', then debug logging for Terragrunt will be enabled. It is recommended that
      you set this input to the 'ACTIONS_RUNNER_DEBUG' secret, so that if debug logging is turned on
      within GitHub Action's UI, debug logging for Terragrunt will also be turned on.
  ref:
    description: The ref of the Action. Don't set this!
    default: ${{ github.action_ref }}