name: Terragrunt Overlay
description: Apply default and overlayed Terragrunt configurations with GitHub Actions.
author: Josh Feierman <josh@sqljosh.com>
runs:
  # using: docker
  # image: 'Dockerfile'
  using: composite
  steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version-file: ${{github.action_path}}/go.mod
    - name: install tgswitch and tfenv
      shell: bash
      run: |
        curl -L https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh | bash -s -- -b ${HOME}/.bin
        echo ${HOME}/.bin >> ${GITHUB_PATH}
        echo "${HOME}/.tfenv/bin" >> ${GITHUB_PATH}
        export PATH=${HOME}/.bin:${HOME}/.tfenv/bin:${PATH}
        tgswitch -b ${HOME}/.bin/terragrunt 0.44.4
        git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
        tfenv use 1.3.9
    - name: run Terragrunt
      run: go build -o ${HOME}/.bin/action-terragrunt main.go
      shell: bash
      working-directory: "${{github.action_path}}"
    - name: run Action
      run: action-terragrunt
      shell: bash
      env:
        INPUT_BASE-DIRECTORY: ${{ inputs.base-directory }}
        INPUT_TERRAFORM-COMMAND: ${{ inputs.terraform-command }}
        INPUT_TOKEN: ${{ inputs.token }}
inputs:
  base-directory:
    description: |
      The base directory for all Terragrunt configurations. Defaults to the root of the
      repository.
    default: "."
    required: false
  terraform-command:
    description: |
      The Terraform command to run.
    required: true
  token:
    description: |
      The token to use when interacting with the GitHub API. This can generally be set to the
      default token.
    required: true
    default: ${{ github.token }}
  ref:
    description: The ref of the Action. Don't set this!
    default: ${{ github.action_ref }}