// Code generated by MockGen. DO NOT EDIT.
// Source: config.go

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	githubactions "github.com/sethvargo/go-githubactions"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// BaseDirectory mocks base method.
func (m *MockConfig) BaseDirectory() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseDirectory")
	ret0, _ := ret[0].(string)
	return ret0
}

// BaseDirectory indicates an expected call of BaseDirectory.
func (mr *MockConfigMockRecorder) BaseDirectory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseDirectory", reflect.TypeOf((*MockConfig)(nil).BaseDirectory))
}

// Command mocks base method.
func (m *MockConfig) Command() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Command")
	ret0, _ := ret[0].(string)
	return ret0
}

// Command indicates an expected call of Command.
func (mr *MockConfigMockRecorder) Command() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Command", reflect.TypeOf((*MockConfig)(nil).Command))
}

// GitHubContext mocks base method.
func (m *MockConfig) GitHubContext() githubactions.GitHubContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitHubContext")
	ret0, _ := ret[0].(githubactions.GitHubContext)
	return ret0
}

// GitHubContext indicates an expected call of GitHubContext.
func (mr *MockConfigMockRecorder) GitHubContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitHubContext", reflect.TypeOf((*MockConfig)(nil).GitHubContext))
}
