on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: run unit tests
        shell: bash
        run: make tools && make generate && make test
      - name: Get Version Number
        id: version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.new_version }}-next
            ${{ github.repository }}:${{ github.sha }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/action-terragrunt:${{ steps.version.outputs.new_version }}-next
      - name: Template action metadata file
        shell: bash
        env:
          GIT_TAG: "${{ steps.version.outputs.new_version }}-next"
          GITHUB_OWNER: "${{ github.repository_owner }}"
        run: |
          make template
      - uses: npalm/action-docs-action@v1.2.0
        with:
          tocLevel: 2
          actionFile: action.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: commit back action changes
        with:
          commit_message: "auto-commit action.yml and README changes"
          file_pattern: action.yaml README.md
          skip_checkout: true
          skip_fetch: true

  integration_test:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: plan test
        uses: ./
        with:
          terraform-command: plan
          base-directory: ./integration/terragrunt/
          token: ${{ secrets.GITHUB_TOKEN }}
          enable-debug-logging: "true"
      - name: apply test
        uses: ./
        with:
          terraform-command: apply
          base-directory: ./integration/terragrunt/
          token: ${{ secrets.GITHUB_TOKEN }}
          enable-debug-logging: "true"
